### ISSUE TITLE
Provider exposes `SECRET_KEY` to the web?

### ISSUE THREAD

**Issue by mirshko** [getuni/react-use-wyre#2]
Hey! 

It seems by using the SECRET key in the Provider, this library exposes your key to the client? 

I'm not 100% if this SECRET key needs to be used on the server side only. 

If this is true, then this should be a warning for the library to not use in a client environment.

**Comment by cawfree** [comment]
Hey there.

Yes, that's correct. Ideally you'd want to create a `bearerToken` on behalf of your end user. This is pretty much just a playground for experimenting with Wyre.
